name: "markov_llm_depth_heads"
method: grid
project: "markov-LLM-depth"
parameters:
  chain:
    values: ["icl"]
  order:
    values: [1]
  n_layer:
    values: [2]
  n_head:
    values: [1]
  n_head_first_layer:
    values: [1]
  n_embd:
    values: [32, 64]  # Merged with previous `n_embd`
  lr: 
    values: [1e-4, 1e-3, 1e-2]  # Merged with new `lr` values
  batch_size_per_chain:
    values: [16, 32, 64]  # Merged with new batch sizes
  num_chains:
    values: [16, 32, 64]
  sequence_length:
    values: [32, 16]  # Merged with new sequence lengths
  iterations:
    values: [30000]
  seed:
    values: [1]
  device:
    values: ["cuda:2"]
  opt:
    values: ["adamw"]  # Merged with new optimizer values
  warmup_percent:
    values: [0.01, 0.02, 0.05]
  weight_decay:
    values: [0, 1e-4, 1e-3]
  dropout:
    values: [0.0]
  scheduler:
    values: ["linear", "cos"]
  beta1:
    values: [0.85, 0.9]
  beta2:
    values: [0.9, 0.95]
  grad_clip:
    values: [0.0, 0.5, 1.0]
  eval_freq:
    values: [6000]
  construction:
    values: ["2-attn-3-mlp"]
  bias:
    values: [false, true]

command:
  - python
  - src/main.py
  - ${args}